spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

openapi:
  resource-server-url: ${RESOURCE_SERVER_URL}
  server-description: Development server